services:
  mysql:
    image: 'mysql:9.2.0'
    container_name: complaint-mysql
    restart: always
    environment:
      - 'MYSQL_DATABASE=complaint_service'
      - 'MYSQL_ROOT_PASSWORD=mysql'
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: 'adminer:5.2.1'
    container_name: adminer-ui
    depends_on:
      - mysql
    restart: always
    ports:
      - "8088:8080"

  complaint-service:
    container_name: complaint-service
    image: 'complaint-service:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/complaint_service
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    depends_on:
      - mysql

  prometheus:
    container_name: prometheus-complaint
    image: prom/prometheus:latest
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    container_name: loki-complaint
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    container_name: grafana-complaint
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus
      - loki
