spring:
  application:
    name: complaint-service

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/complaint_service
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    path: /
    url: /api-docs.yml

# Observability & Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: ${spring.application.name}

# Loki
loki:
  url: http://localhost:3100/loki/api/v1/push
