global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'complaint-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['complaint-service:8080']
